config/routes.rb
Rails.application.routes.draw do

  get 'logbooks/new'

  get 'logbooks/index'

  get 'logbooks/show'

  root 'posts#index'
  resources :logbooks

  devise_for :users

end

app/models/airport.rb
class Airport < ActiveRecord::Base
	belongs_to :logbooks
	
end

app/models/logbook.rb
class Logbook < ActiveRecord::Base
	has_many :airports
	belongs_to :user


	before_validation :uppercase_dep_arr

	def uppercase_dep_arr
		departurePlace.upcase!
		arrivalPlace.upcase!
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :logbooks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logbooks_controller.rb
class LogbooksController < ApplicationController

  def new
  	@Logbook = Logbook.new

  end

  def index
    @Logbook = Logbook.all

    @logs_grid = initialize_grid(Logbook, name: 'logs', conditions: ["logbooks.user_id = ? ", current_user.id],  enable_export_to_csv: true,
      csv_file_name: 'logbook', order: 'logbooks.created_at', order_direction: 'desc')

    export_grid_if_requested('logs' => 'logs_grid')
  end

  def show
    @Logbook = Logbook.find(params[:id])

    #Departure Airport
    @lat_dep = Airport.where(ident: @Logbook.departurePlace).pluck(:latitude).first
    @long_dep = Airport.where(ident: @Logbook.departurePlace).pluck(:longitude).first

    #Arrival Airport
    @lat_arr = Airport.where(ident: @Logbook.arrivalPlace).pluck(:latitude).first
    @long_arr = Airport.where(ident: @Logbook.arrivalPlace).pluck(:longitude).first

    @distance = ((Geocoder::Calculations.distance_between([@lat_dep, @long_dep], [@lat_arr, @long_arr])) * 0.868976).round(1)
  end

  def create
  	#Submitting logbook entry form
  	@Logbook = Logbook.new(permit_logbook)
    @Logbook.user_id = current_user.id
   

  	if @Logbook.save
  		flash[:success] = "Log successfully added!"
  		redirect_to logbooks_path
  	else
  		flash[:error] = @Logbook.errors.full_messages
  		redirect_to new_logbook_path

  	end
  end

  def edit
    @Logbook = Logbook.find(params[:id])
  end

  def update
    @Logbook = Logbook.find(params[:id])
    if @Logbook.update_attributes(permit_logbook)
      flash[:success] = "Log successfully updated!"
      redirect_to logbooks_path
    else
      flash[:error] = @Logbook.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @Logbook = Logbook.find(params[:id])
    
    if @Logbook.destroy
    	flash[:success] = "Log successfully deleted"
		redirect_to logbooks_path
	else
		flash[:error] = "Log could not be deleted"
		redirect_to new_logbooks_path

	end
  end
  private
  	def permit_logbook
  		params.require(:logbook).permit(:date, :departurePlace, :departureTime, :arrivalPlace,
       :arrivalTime, :aircraftType, :aircraftReg, :engine_type, :multipilot_time, :flightTime, :PIC, :day_takeoff,
       :night_takeoff, :day_landing, :night_landing, :night_time, :ifr_time, :pic_time, :copilot_time,
       :dual_time, :instructor_time, :sim_date, :simtype, :sim_time, :remarks)
  	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@post = Post.new
  end

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logbooks_helper.rb
module LogbooksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LogbookApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>

<style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */


    }
    </style>


</head>
<body>




 <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <%= link_to "LogbookApp", root_url, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to "Add log", new_logbook_path %>
                    </li>
                    <%- if current_user %>
                    <li>
                        <%= link_to "Logbook", logbooks_path %>
                    </li>

                    <li>
                        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                    </li>


                    <% else %>
                    <li>
                        <%= link_to "Login", new_user_session_path %>
                    </li>
                    <li>
                        <%= link_to "Register", new_user_registration_path %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
                <% flash.each do |a, b| %>
                    <div class="alert alert-success"> <%= b %> </div>
                <% end %>
            <%= yield %>
            </div>

        <div class ="page-hold">
        </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->



</body>
</html>

app/views/logbooks/_logs_grid.html.erb
<%= grid(@logs_grid, hide_csv_button: true) do |g|
  # HTML Version
  g.column in_csv: false, name: "Date", ordering: true, filter: true do |task|
    link_to(task.date.try(:strftime, '%d/%m/%Y'), logbook_path(task))
  end
  # CSV Version
  g.column in_html: false, name: "Date", ordering: true, filter: true do |task|
    task.date.try(:strftime, '%d/%m/%Y')
  end
  g.column name: "From" do |task|
    task.departurePlace
  end
   g.column name: "Dep. Time" do |task|
    task.departureTime.try(:strftime, '%H:%M')
  end
   g.column name: "To" do |task|
    task.arrivalPlace
  end
  g.column name: "Arr. Time" do |task|
    task.arrivalTime.try(:strftime, '%H:%M')
  end
  g.column name: "Type" do |task|
    task.aircraftType
  end
  g.column name: "Reg" do |task|
    task.aircraftReg
  end
  g.column name: "SE/ME" do |task|
    task.engine_type
  end
  g.column name: "Name PIC"  do |task|
    task.PIC
  end
  g.column name: "Total Time" do |task|
    task.flightTime
  end
  g.column name: "Day TO"  do |task|
    task.day_takeoff
  end
  g.column name: "Night TO"  do |task|
    task.night_takeoff
  end
  g.column name: "Day L"  do |task|
    task.day_landing
  end
  g.column name: "Night L"  do |task|
    task.night_landing
  end
  g.column name: "Night"  do |task|
    task.night_time
  end
  g.column name: "IFR"  do |task|
    task.ifr_time
  end
  g.column name: "PIC"  do |task|
    task.pic_time
  end
  g.column name: "Co-Pilot"  do |task|
    task.copilot_time
  end
  g.column name: "Dual"  do |task|
    task.dual_time
  end
  g.column name: "Instr."  do |task|
    task.instructor_time
  end
  g.column name: "SIM"  do |task|
    task.sim_time
  end
  g.column in_csv: false do |task|
    link_to('Edit',  edit_logbook_path(task))
  end
   g.column in_csv: false do |task|
    link_to("Delete", task,  method: :delete)
  end
  g.last_row do |rec|         # This row will always be added to the bottom of the grid
    '<tr><td>' +'Total' + '</td><td colspan = 8>' + '</td><td>' + @Logbook.sum(:flightTime).to_s + '</td><td>' + @Logbook.sum(:day_takeoff).to_s + '</td><td>' + @Logbook.sum(:night_takeoff).to_s + '</td><td>' + @Logbook.sum(:day_landing).to_s + '</td><td>' + @Logbook.sum(:night_landing).to_s + '</td><td>' + @Logbook.sum(:night_time).to_s + '</td><td>' + @Logbook.sum(:ifr_time).to_s + '</td><td>' + @Logbook.sum(:pic_time).to_s + '</td><td>' + @Logbook.sum(:copilot_time).to_s + '</td><td>' + @Logbook.sum(:dual_time).to_s + '</td><td>' + @Logbook.sum(:instructor_time).to_s + '</td><td>' + @Logbook.sum(:sim_time).to_s + '</td></tr>'
  end
end -%>

app/views/logbooks/edit.html.erb
<h1>Add new log</h1>



<%= form_for @Logbook do |f| %>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<h3> Departure </h3>
	<%= f.label :departure_airport, "Airport"%>
	<%= f.text_field :departurePlace, size: 4, maxlength: 4, required: true %>

	<%= f.label :departure_Time, "Time" %>
	<%= f.time_field :departureTime%>

	<h3> Arrival </h3>
	<%= f.label :arrival_airport, "Airport" %>
	<%= f.text_field :arrivalPlace, size: 4, maxlength: 4 %>

	<%= f.label :arrival_time, "Time" %>
	<%= f.time_field :arrivalTime %>

	<h3> Aircraft </h3>

	<%= f.label :aircraft_type, "Aircraft Type" %>
	<%= f.text_field :aircraftType, size: 5  %>

	<%= f.label :aircraft_registration, "Aircraft Reg." %>
	<%= f.text_field :aircraftReg, size: 5 %>

	<br><br>

	<%= f.label :SE, "SE" %>
	<%= f.radio_button :engine_type, "SE" %>
	<%= f.label :ME, "ME" %>
	<%= f.radio_button :engine_type, 'ME' %>

	<%= f.label :multipilot_time, "Multi-Pilot Time" %>
	<%= f.time_field :multipilot_time %>

	<%= f.label :total_time, "Total Flight" %>
	<%= f.time_field :flightTime %>

	<%= f.label :PIC_name, "Name PIC" %>
	<%= f.text_field :PIC, size: 20 %>

	<h3> Take Offs</h3>
	<%= f.label :day %>
	<%= f.number_field :day_takeoff, value: 0, min: 0, max: 50 %>

	<%= f.label :night %>
	<%= f.number_field :day_takeoff, value: 0, min: 0, max: 50 %>

	<h3> Landings</h3>
	<%= f.label :day %>
	<%= f.number_field :day_landing, value: 0, min: 0, max: 50 %>

	<%= f.label :night %>
	<%= f.number_field :night_landing, value: 0, min: 0, max: 50 %>

	<h3> Operational Condition Time</h3>
	<%= f.label :Night %>
	<%= f.time_field :night_time %>

	<%= f.label :ifr, "IFR" %>
	<%= f.time_field :ifr_time %>

	<h3> Pilot Function Time </h3>
	<%= f.label :pic, "PIC" %>
	<%= f.time_field :pic_time %>

	<%= f.label :copilot, "Co-Pilot" %>
	<%= f.time_field :copilot_time %>

	<%= f.label :dual %>
	<%= f.time_field :dual_time %>

	<%= f.label :instructor %>
	<%= f.time_field :instructor_time %>
	
	<h3> Synthetic Training Devices Session</h3>
	<%= f.label :date %>
	<%= f.date_field :sim_date %>

	<%= f.label :type %>
	<%= f.text_field :simtype, size: 10  %>

	<%= f.label :totaltime, "Total Time of Session" %>
	<%= f.time_field :sim_time %>

	<br><br>
	<%= f.label :remarks %>
	<%= f.text_field :remarks, size: 10  %>
	<br><br>
	<%= f.submit%>
<% end %>

app/views/logbooks/index.html.erb
<div class ="page-hold">
	<h1><%= current_user.email %>'s Logbook</h1>
 <p> Total flights: <%=  Logbook.count('id', distinct: true) %> </p>

<br>
<%= render partial: 'logs_grid' %>
<button class="wg-external-csv-export-button" data-grid-name="logs">Export To CSV</button>

</div>

app/views/logbooks/new.html.erb
<h1>Add new log</h1>



<%= form_for @Logbook do |f| %>
	<%= f.label :date, class: "required" %>
	<%= f.date_field :date %>
	<h3> Departure </h3>
	<%= f.label :departure_airport, "Airport", class: "required" %>
	<%= f.text_field :departurePlace, size: 4, maxlength: 4, required: false %>

	<%= f.label :departure_Time, "Time", class: "required" %>
	<%= f.time_field :departureTime%>

	<h3> Arrival </h3>
	<%= f.label :arrival_airport, "Airport", class: "required" %>
	<%= f.text_field :arrivalPlace, size: 4, maxlength: 4 %>

	<%= f.label :arrival_time, "Time", class: "required" %>
	<%= f.time_field :arrivalTime %>

	<h3> Aircraft </h3>

	<%= f.label :aircraft_type, "Aircraft Type", class: "required" %>
	<%= f.text_field :aircraftType, size: 5  %>

	<%= f.label :aircraft_registration, "Aircraft Reg.", class: "required" %>
	<%= f.text_field :aircraftReg, size: 5 %>

	<br><br>

	<%= f.label :SE, "SE" %>
	<%= f.radio_button :engine_type, "SE" %>
	<%= f.label :ME, "ME" %>
	<%= f.radio_button :engine_type, 'ME' %>

	<%= f.label :multipilot_time, "Multi-Pilot Time" %>
	<%= f.number_field :multipilot_time %>

	<%= f.label :total_time, "Total Flight", class: "required" %>
	<%= f.number_field :flightTime, min: 0, step: 0.01 %>

	<%= f.label :PIC_name, "Name PIC", class: "required" %>
	<%= f.text_field :PIC, size: 20 %>

	<h3> Take Offs</h3>
	<%= f.label :day %>
	<%= f.number_field :day_takeoff, min: 0, max: 50 %>

	<%= f.label :night %>
	<%= f.number_field :day_takeoff, min: 0, max: 50 %>

	<h3> Landings</h3>
	<%= f.label :day %>
	<%= f.number_field :day_landing, min: 0, max: 50 %>

	<%= f.label :night %>
	<%= f.number_field :night_landing, min: 0, max: 50 %>

	<h3> Operational Condition Time</h3>
	<%= f.label :Night %>
	<%= f.number_field :night_time, min: 0, step: 0.01 %>

	<%= f.label :ifr, "IFR" %>
	<%= f.number_field :ifr_time, min: 0, step: 0.01 %>

	<h3> Pilot Function Time </h3>
	<%= f.label :pic, "PIC" %>
	<%= f.number_field :pic_time, min: 0, step: 0.01 %>

	<%= f.label :copilot, "Co-Pilot" %>
	<%= f.number_field :copilot_time, min: 0, step: 0.01%>

	<%= f.label :dual %>
	<%= f.number_field :dual_time, min: 0, step: 0.01 %>

	<%= f.label :instructor %>
	<%= f.number_field :instructor_time, min: 0, step: 0.01 %>
	
	<h3> Synthetic Training Devices Session</h3>
	<%= f.label :date %>
	<%= f.date_field :sim_date %>

	<%= f.label :type %>
	<%= f.text_field :simtype, size: 10  %>

	<%= f.label :totaltime, "Total Time of Session" %>
	<%= f.number_field :sim_time, min: 0, step: 0.01 %>

	<br><br>
	<%= f.label :remarks %>
	<%= f.text_field :remarks, size: 10  %>
	<br><br>
	<%= f.submit%>
<% end %>

app/views/logbooks/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&key=[api]"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<h1><%= @Logbook.departurePlace %> - <%= @Logbook.arrivalPlace %></h1>

<h5><b><%= @distance %> nm </b></h5>




<br>
<div style='width: 800px; margin: 0 auto; padding-bottom: 15px;'>
  <div id="map" style='width: 800px; height: 300px;'>
    
    <script type="text/javascript">
 

var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 3,
    center: {lat: 0, lng: 0},
    mapTypeId: google.maps.MapTypeId.TERRAIN
  });
  
  var coordinates = [
  [<%= @lat_dep %>,<%= @long_dep %>],
  [<%= @lat_arr %>,<%= @long_arr %>]
  ];

  var flightPlanCoordinates = []

  var bounds = new google.maps.LatLngBounds();
  
   for( i = 0; i < coordinates.length; i++ ) {
        var position = new google.maps.LatLng(coordinates[i][0], coordinates[i][1]);
        bounds.extend(position);

        marker = new google.maps.Marker({
            position: position,
            map: map,
        });

        flightPlanCoordinates.push(marker.getPosition());
    }

  map.fitBounds(bounds);

  var flightPath = new google.maps.Polyline({
    path: flightPlanCoordinates,
    geodesic: true,
    strokeColor: '#FF0000',
    strokeOpacity: 1.0,
    strokeWeight: 2
  });

  flightPath.setMap(map);

</script>
  </div>
</div>


<table class="table table-bordered">       
<h4><%= @Logbook.date.try(:strftime, '%d/%m/%Y') %></h4>                  
  <tr>   
  	<th>Departure Time</th>
  	<th>Arival Time</th>
  </tr>
  <tr>
	<td><%= @Logbook.departureTime.try(:strftime, '%H:%M') %></td>
	<td><%= @Logbook.arrivalTime.try(:strftime, '%H:%M') %></td>
  </tr>

   

</table> 

<table class="table table-bordered">  
<tr>   
  	<th>Type</th>
  	<th>Registration</th>
  	<th>SE/ME</th>
  </tr>

  <tr>
	<td><%= @Logbook.aircraftType %></td>
	<td><%= @Logbook.aircraftReg %></td>
	<td><%= @Logbook.engine_type %></td>

  </tr>
  </table>

  <table class="table table-bordered">  
<tr>   
  	<th colspan="2">Take Offs</th>
  	<th colspan="2">Landings</th>

  </tr>

  <tr>
  <th>Day</th>
  <th>Night</th>
  <th>Day</th>
  <th>Night</th>
  </tr>

  <tr>
	<td><%= @Logbook.day_takeoff %></td>
	<td><%= @Logbook.night_takeoff %></td>
	<td><%= @Logbook.day_landing %></td>
	<td><%= @Logbook.night_landing %></td>


  </tr>
  </table>

  <table class="table table-bordered">  
<tr>   
  	<th>Night</th>
  	<th>PIC</th>
  	<th>Co-Pilot</th>
  	<th>Dual</th>
  	<th>Instructor</th>
  </tr>

  <tr>
	<td><%= @Logbook.night_time %></td>
	<td><%= @Logbook.pic_time %></td>
	<td><%= @Logbook.copilot_time %></td>
	<td><%= @Logbook.dual_time %></td>
	<td><%= @Logbook.instructor_time %></td>

  </tr>
  </table>

  <table class="table table-bordered">  
<tr>   
  	<th>Date</th>
  	<th>Type</th>
  	<th>Time</th>

  </tr>

  <tr>
	<td><%= @Logbook.sim_date %></td>
	<td><%= @Logbook.simtype %></td>
	<td><%= @Logbook.sim_time %></td>
  </tr>

  
  </table>
 <table class="table table-bordered">  
<tr>   
    <th>Remarks</th>


  </tr>

  <tr>
  <td><%= @Logbook.remarks %></td>
  </tr>

  
  </table>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_for @post do |f| %>
<%= f.label :description %>
<%= f.datearea :date %>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>